/**
 * API Inspector
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include <corvusoft/restbed/byte.hpp>
#include <corvusoft/restbed/string.hpp>
#include <corvusoft/restbed/settings.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/uri.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/algorithm/string.hpp>

#include "MachineLearningModelGyMApi.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

namespace {
[[maybe_unused]]
std::string selectPreferredContentType(const std::vector<std::string>& contentTypes) {
    if (contentTypes.size() == 0) {
        return "application/json";
    }

    if (contentTypes.size() == 1) {
        return contentTypes.at(0);
    }

    static const std::array<std::string, 2> preferredTypes = {"json", "xml"};
    for (const auto& preferredType: preferredTypes) {
        const auto ret = std::find_if(contentTypes.cbegin(),
        contentTypes.cend(),
        [preferredType](const std::string& str) {
            return str.find(preferredType) != std::string::npos;});
        if (ret != contentTypes.cend()) {
            return *ret;
        }
    }

    return contentTypes.at(0);
}
}

MachineLearningModelGyMApiException::MachineLearningModelGyMApiException(int status_code, std::string what)
  : m_status(status_code),
    m_what(what)
{

}
int MachineLearningModelGyMApiException::getStatus() const
{
    return m_status;
}
const char* MachineLearningModelGyMApiException::what() const noexcept
{
    return m_what.c_str();
}


template<class MODEL_T>
MODEL_T extractJsonModelBodyParam(const std::string& bodyContent)
{
    std::stringstream sstream(bodyContent);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream, pt);

    auto model = MODEL_T(pt);
    return model;
}

template<class MODEL_T>
std::vector<MODEL_T> extractJsonArrayBodyParam(const std::string& bodyContent)
{
    std::stringstream sstream(bodyContent);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream, pt);

    auto arrayRet = std::vector<MODEL_T>();
    for (const auto& child: pt) {
        arrayRet.emplace_back(MODEL_T(child.second));
    }
    return arrayRet;
}

template <class KEY_T, class VAL_T>
std::string convertMapResponse(const std::map<KEY_T, VAL_T>& map)
{
    boost::property_tree::ptree pt;
    for(const auto &kv: map) {
    pt.push_back(boost::property_tree::ptree::value_type(
        boost::lexical_cast<std::string>(kv.first),
        boost::property_tree::ptree(
        boost::lexical_cast<std::string>(kv.second))));
    }
    std::stringstream sstream;
    write_json(sstream, pt);
    std::string result = sstream.str();
    return result;
}

namespace MachineLearningModelGyMApiResources {
MachineLearningModelGyMResource::MachineLearningModelGyMResource(const std::string& context /* = "/openapi-jaxrs-server-1.0.0/api/v3" */)
{
	this->set_path(context + "/machineLearningModelGyM");
	this->set_method_handler("POST",
		std::bind(&MachineLearningModelGyMResource::handler_POST_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> MachineLearningModelGyMResource::handleMachineLearningModelGyMApiException(const MachineLearningModelGyMApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> MachineLearningModelGyMResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> MachineLearningModelGyMResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void MachineLearningModelGyMResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void MachineLearningModelGyMResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void MachineLearningModelGyMResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void MachineLearningModelGyMResource::handler_POST_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // body params or form params here from the body content string
    std::string bodyContent = extractBodyContent(session);
    auto machineLearningModelGym = extractJsonModelBodyParam<MachineLearningModelGym>(bodyContent);
    
    int status_code = 500;
    MachineLearningModelGym resultObject = MachineLearningModelGym{};
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_POST(machineLearningModelGym);
    }
    catch(const MachineLearningModelGyMApiException& e) {
        std::tie(status_code, result) = handleMachineLearningModelGyMApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json","application/xml",
    };
    static const std::string acceptTypes{
        "application/json, application/xml, application/x-www-form-urlencoded, "
    };
    
    if (status_code == 0) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "successful operation";
    
        result = resultObject.toJsonString();
        returnResponse(session, 0, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
}


std::pair<int, MachineLearningModelGym> MachineLearningModelGyMResource::handler_POST(
        MachineLearningModelGym & machineLearningModelGym)
{
    return handler_POST_func(machineLearningModelGym);
}


std::string MachineLearningModelGyMResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string MachineLearningModelGyMResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
MachineLearningModelGyMCreateWithListResource::MachineLearningModelGyMCreateWithListResource(const std::string& context /* = "/openapi-jaxrs-server-1.0.0/api/v3" */)
{
	this->set_path(context + "/machineLearningModelGyM/createWithList");
	this->set_method_handler("POST",
		std::bind(&MachineLearningModelGyMCreateWithListResource::handler_POST_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> MachineLearningModelGyMCreateWithListResource::handleMachineLearningModelGyMApiException(const MachineLearningModelGyMApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> MachineLearningModelGyMCreateWithListResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> MachineLearningModelGyMCreateWithListResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void MachineLearningModelGyMCreateWithListResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void MachineLearningModelGyMCreateWithListResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void MachineLearningModelGyMCreateWithListResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void MachineLearningModelGyMCreateWithListResource::handler_POST_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // body params or form params here from the body content string
    std::string bodyContent = extractBodyContent(session);
    auto machineLearningModelGym = extractJsonArrayBodyParam<MachineLearningModelGym>(bodyContent);
    
    int status_code = 500;
    MachineLearningModelGym resultObject = MachineLearningModelGym{};
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_POST(machineLearningModelGym);
    }
    catch(const MachineLearningModelGyMApiException& e) {
        std::tie(status_code, result) = handleMachineLearningModelGyMApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json","application/xml",
    };
    static const std::string acceptTypes{
        "application/json, "
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        result = resultObject.toJsonString();
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 0) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "successful operation";
    
        returnResponse(session, 0, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
}


std::pair<int, MachineLearningModelGym> MachineLearningModelGyMCreateWithListResource::handler_POST(
        std::vector<MachineLearningModelGym> & machineLearningModelGym)
{
    return handler_POST_func(machineLearningModelGym);
}


std::string MachineLearningModelGyMCreateWithListResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string MachineLearningModelGyMCreateWithListResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
MachineLearningModelGyMNameResource::MachineLearningModelGyMNameResource(const std::string& context /* = "/openapi-jaxrs-server-1.0.0/api/v3" */)
{
	this->set_path(context + "/machineLearningModelGyM/{name: .*}");
	this->set_method_handler("DELETE",
		std::bind(&MachineLearningModelGyMNameResource::handler_DELETE_internal, this,
			std::placeholders::_1));
	this->set_method_handler("GET",
		std::bind(&MachineLearningModelGyMNameResource::handler_GET_internal, this,
			std::placeholders::_1));
	this->set_method_handler("PUT",
		std::bind(&MachineLearningModelGyMNameResource::handler_PUT_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> MachineLearningModelGyMNameResource::handleMachineLearningModelGyMApiException(const MachineLearningModelGyMApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> MachineLearningModelGyMNameResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> MachineLearningModelGyMNameResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void MachineLearningModelGyMNameResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void MachineLearningModelGyMNameResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void MachineLearningModelGyMNameResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void MachineLearningModelGyMNameResource::handler_DELETE_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // Getting the path params
    std::string name = request->get_path_parameter("name", "");
    
    int status_code = 500;
    std::string result = "";
    
    try {
        status_code =
            handler_DELETE(name);
    }
    catch(const MachineLearningModelGyMApiException& e) {
        std::tie(status_code, result) = handleMachineLearningModelGyMApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json"
    };
    static const std::string acceptTypes{
    };
    
    if (status_code == 400) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Invalid MachineLearningModelGym variable supplied";
    
        returnResponse(session, 400, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 404) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "MachineLearningModelGym not found";
    
        returnResponse(session, 404, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
}

// x-extension
void MachineLearningModelGyMNameResource::handler_GET_internal(const std::shared_ptr<restbed::Session> session) {
    const auto request = session->get_request();
    // Getting the path params
    std::string name = request->get_path_parameter("name", "");
    
    int status_code = 500;
    MachineLearningModelGym resultObject = MachineLearningModelGym{};
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_GET(name);
    }
    catch(const MachineLearningModelGyMApiException& e) {
        std::tie(status_code, result) = handleMachineLearningModelGyMApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json","application/xml",
    };
    static const std::string acceptTypes{
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        result = resultObject.toJsonString();
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 400) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Invalid MachineLearningModelGym variable supplied";
    
        returnResponse(session, 400, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 404) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "MachineLearningModelGym not found";
    
        returnResponse(session, 404, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
}
// x-extension
void MachineLearningModelGyMNameResource::handler_PUT_internal(const std::shared_ptr<restbed::Session> session) {
    const auto request = session->get_request();
    // body params or form params here from the body content string
    std::string bodyContent = extractBodyContent(session);
    auto machineLearningModelGym = extractJsonModelBodyParam<MachineLearningModelGym>(bodyContent);
    // Getting the path params
    std::string name = request->get_path_parameter("name", "");
    
    int status_code = 500;
    std::string result = "";
    
    try {
        status_code =
            handler_PUT(name, machineLearningModelGym);
    }
    catch(const MachineLearningModelGyMApiException& e) {
        std::tie(status_code, result) = handleMachineLearningModelGyMApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json"
    };
    static const std::string acceptTypes{
        "application/json, application/xml, application/x-www-form-urlencoded, "
    };
    
    if (status_code == 0) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "successful operation";
    
        returnResponse(session, 0, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
}

int MachineLearningModelGyMNameResource::handler_DELETE(
        std::string & name)
{
    return handler_DELETE_func(name);
}

std::pair<int, MachineLearningModelGym> MachineLearningModelGyMNameResource::handler_GET(
    std::string & name)
{
    return handler_GET_func(name);
}
int MachineLearningModelGyMNameResource::handler_PUT(
    std::string & name, MachineLearningModelGym & machineLearningModelGym)
{
    return handler_PUT_func(name, machineLearningModelGym);
}

std::string MachineLearningModelGyMNameResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string MachineLearningModelGyMNameResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}

} /* namespace MachineLearningModelGyMApiResources */

MachineLearningModelGyMApi::MachineLearningModelGyMApi(std::shared_ptr<restbed::Service> const& restbedService)
: m_service(restbedService)
{
}

MachineLearningModelGyMApi::~MachineLearningModelGyMApi() {}

std::shared_ptr<MachineLearningModelGyMApiResources::MachineLearningModelGyMResource> MachineLearningModelGyMApi::getMachineLearningModelGyMResource() {
    if (!m_spMachineLearningModelGyMResource) {
        setResource(std::make_shared<MachineLearningModelGyMApiResources::MachineLearningModelGyMResource>());
    }
    return m_spMachineLearningModelGyMResource;
}
std::shared_ptr<MachineLearningModelGyMApiResources::MachineLearningModelGyMCreateWithListResource> MachineLearningModelGyMApi::getMachineLearningModelGyMCreateWithListResource() {
    if (!m_spMachineLearningModelGyMCreateWithListResource) {
        setResource(std::make_shared<MachineLearningModelGyMApiResources::MachineLearningModelGyMCreateWithListResource>());
    }
    return m_spMachineLearningModelGyMCreateWithListResource;
}
std::shared_ptr<MachineLearningModelGyMApiResources::MachineLearningModelGyMNameResource> MachineLearningModelGyMApi::getMachineLearningModelGyMNameResource() {
    if (!m_spMachineLearningModelGyMNameResource) {
        setResource(std::make_shared<MachineLearningModelGyMApiResources::MachineLearningModelGyMNameResource>());
    }
    return m_spMachineLearningModelGyMNameResource;
}
void MachineLearningModelGyMApi::setResource(std::shared_ptr<MachineLearningModelGyMApiResources::MachineLearningModelGyMResource> resource) {
    m_spMachineLearningModelGyMResource = resource;
    m_service->publish(m_spMachineLearningModelGyMResource);
}
void MachineLearningModelGyMApi::setResource(std::shared_ptr<MachineLearningModelGyMApiResources::MachineLearningModelGyMCreateWithListResource> resource) {
    m_spMachineLearningModelGyMCreateWithListResource = resource;
    m_service->publish(m_spMachineLearningModelGyMCreateWithListResource);
}
void MachineLearningModelGyMApi::setResource(std::shared_ptr<MachineLearningModelGyMApiResources::MachineLearningModelGyMNameResource> resource) {
    m_spMachineLearningModelGyMNameResource = resource;
    m_service->publish(m_spMachineLearningModelGyMNameResource);
}
void MachineLearningModelGyMApi::setMachineLearningModelGyMApiMachineLearningModelGyMResource(std::shared_ptr<MachineLearningModelGyMApiResources::MachineLearningModelGyMResource> spMachineLearningModelGyMResource) {
    m_spMachineLearningModelGyMResource = spMachineLearningModelGyMResource;
    m_service->publish(m_spMachineLearningModelGyMResource);
}
void MachineLearningModelGyMApi::setMachineLearningModelGyMApiMachineLearningModelGyMCreateWithListResource(std::shared_ptr<MachineLearningModelGyMApiResources::MachineLearningModelGyMCreateWithListResource> spMachineLearningModelGyMCreateWithListResource) {
    m_spMachineLearningModelGyMCreateWithListResource = spMachineLearningModelGyMCreateWithListResource;
    m_service->publish(m_spMachineLearningModelGyMCreateWithListResource);
}
void MachineLearningModelGyMApi::setMachineLearningModelGyMApiMachineLearningModelGyMNameResource(std::shared_ptr<MachineLearningModelGyMApiResources::MachineLearningModelGyMNameResource> spMachineLearningModelGyMNameResource) {
    m_spMachineLearningModelGyMNameResource = spMachineLearningModelGyMNameResource;
    m_service->publish(m_spMachineLearningModelGyMNameResource);
}


void MachineLearningModelGyMApi::publishDefaultResources() {
    if (!m_spMachineLearningModelGyMResource) {
        setResource(std::make_shared<MachineLearningModelGyMApiResources::MachineLearningModelGyMResource>());
    }
    if (!m_spMachineLearningModelGyMCreateWithListResource) {
        setResource(std::make_shared<MachineLearningModelGyMApiResources::MachineLearningModelGyMCreateWithListResource>());
    }
    if (!m_spMachineLearningModelGyMNameResource) {
        setResource(std::make_shared<MachineLearningModelGyMApiResources::MachineLearningModelGyMNameResource>());
    }
}

std::shared_ptr<restbed::Service> MachineLearningModelGyMApi::service() {
    return m_service;
}


}
}
}
}

