/**
 * API Inspector
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include <corvusoft/restbed/byte.hpp>
#include <corvusoft/restbed/string.hpp>
#include <corvusoft/restbed/settings.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/uri.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/algorithm/string.hpp>

#include "MetalRefineryApi.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

namespace {
[[maybe_unused]]
std::string selectPreferredContentType(const std::vector<std::string>& contentTypes) {
    if (contentTypes.size() == 0) {
        return "application/json";
    }

    if (contentTypes.size() == 1) {
        return contentTypes.at(0);
    }

    static const std::array<std::string, 2> preferredTypes = {"json", "xml"};
    for (const auto& preferredType: preferredTypes) {
        const auto ret = std::find_if(contentTypes.cbegin(),
        contentTypes.cend(),
        [preferredType](const std::string& str) {
            return str.find(preferredType) != std::string::npos;});
        if (ret != contentTypes.cend()) {
            return *ret;
        }
    }

    return contentTypes.at(0);
}
}

MetalRefineryApiException::MetalRefineryApiException(int status_code, std::string what)
  : m_status(status_code),
    m_what(what)
{

}
int MetalRefineryApiException::getStatus() const
{
    return m_status;
}
const char* MetalRefineryApiException::what() const noexcept
{
    return m_what.c_str();
}


template<class MODEL_T>
MODEL_T extractJsonModelBodyParam(const std::string& bodyContent)
{
    std::stringstream sstream(bodyContent);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream, pt);

    auto model = MODEL_T(pt);
    return model;
}

template<class MODEL_T>
std::vector<MODEL_T> extractJsonArrayBodyParam(const std::string& bodyContent)
{
    std::stringstream sstream(bodyContent);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream, pt);

    auto arrayRet = std::vector<MODEL_T>();
    for (const auto& child: pt) {
        arrayRet.emplace_back(MODEL_T(child.second));
    }
    return arrayRet;
}

template <class KEY_T, class VAL_T>
std::string convertMapResponse(const std::map<KEY_T, VAL_T>& map)
{
    boost::property_tree::ptree pt;
    for(const auto &kv: map) {
    pt.push_back(boost::property_tree::ptree::value_type(
        boost::lexical_cast<std::string>(kv.first),
        boost::property_tree::ptree(
        boost::lexical_cast<std::string>(kv.second))));
    }
    std::stringstream sstream;
    write_json(sstream, pt);
    std::string result = sstream.str();
    return result;
}

namespace MetalRefineryApiResources {
MetalRefineryResource::MetalRefineryResource(const std::string& context /* = "/openapi-jaxrs-server-1.0.0/api/v3" */)
{
	this->set_path(context + "/metalRefinery");
	this->set_method_handler("POST",
		std::bind(&MetalRefineryResource::handler_POST_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> MetalRefineryResource::handleMetalRefineryApiException(const MetalRefineryApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> MetalRefineryResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> MetalRefineryResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void MetalRefineryResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void MetalRefineryResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void MetalRefineryResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void MetalRefineryResource::handler_POST_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // body params or form params here from the body content string
    std::string bodyContent = extractBodyContent(session);
    auto metalRefinery = extractJsonModelBodyParam<MetalRefinery>(bodyContent);
    
    int status_code = 500;
    MetalRefinery resultObject = MetalRefinery{};
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_POST(metalRefinery);
    }
    catch(const MetalRefineryApiException& e) {
        std::tie(status_code, result) = handleMetalRefineryApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json","application/xml",
    };
    static const std::string acceptTypes{
        "application/json, application/xml, application/x-www-form-urlencoded, "
    };
    
    if (status_code == 0) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "successful operation";
    
        result = resultObject.toJsonString();
        returnResponse(session, 0, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
}


std::pair<int, MetalRefinery> MetalRefineryResource::handler_POST(
        MetalRefinery & metalRefinery)
{
    return handler_POST_func(metalRefinery);
}


std::string MetalRefineryResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string MetalRefineryResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
MetalRefineryCreateWithListResource::MetalRefineryCreateWithListResource(const std::string& context /* = "/openapi-jaxrs-server-1.0.0/api/v3" */)
{
	this->set_path(context + "/metalRefinery/createWithList");
	this->set_method_handler("POST",
		std::bind(&MetalRefineryCreateWithListResource::handler_POST_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> MetalRefineryCreateWithListResource::handleMetalRefineryApiException(const MetalRefineryApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> MetalRefineryCreateWithListResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> MetalRefineryCreateWithListResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void MetalRefineryCreateWithListResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void MetalRefineryCreateWithListResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void MetalRefineryCreateWithListResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void MetalRefineryCreateWithListResource::handler_POST_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // body params or form params here from the body content string
    std::string bodyContent = extractBodyContent(session);
    auto metalRefinery = extractJsonArrayBodyParam<MetalRefinery>(bodyContent);
    
    int status_code = 500;
    MetalRefinery resultObject = MetalRefinery{};
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_POST(metalRefinery);
    }
    catch(const MetalRefineryApiException& e) {
        std::tie(status_code, result) = handleMetalRefineryApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json","application/xml",
    };
    static const std::string acceptTypes{
        "application/json, "
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        result = resultObject.toJsonString();
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 0) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "successful operation";
    
        returnResponse(session, 0, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
}


std::pair<int, MetalRefinery> MetalRefineryCreateWithListResource::handler_POST(
        std::vector<MetalRefinery> & metalRefinery)
{
    return handler_POST_func(metalRefinery);
}


std::string MetalRefineryCreateWithListResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string MetalRefineryCreateWithListResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
MetalRefineryNameResource::MetalRefineryNameResource(const std::string& context /* = "/openapi-jaxrs-server-1.0.0/api/v3" */)
{
	this->set_path(context + "/metalRefinery/{name: .*}");
	this->set_method_handler("DELETE",
		std::bind(&MetalRefineryNameResource::handler_DELETE_internal, this,
			std::placeholders::_1));
	this->set_method_handler("GET",
		std::bind(&MetalRefineryNameResource::handler_GET_internal, this,
			std::placeholders::_1));
	this->set_method_handler("PUT",
		std::bind(&MetalRefineryNameResource::handler_PUT_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> MetalRefineryNameResource::handleMetalRefineryApiException(const MetalRefineryApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> MetalRefineryNameResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> MetalRefineryNameResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void MetalRefineryNameResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void MetalRefineryNameResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void MetalRefineryNameResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void MetalRefineryNameResource::handler_DELETE_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // Getting the path params
    std::string name = request->get_path_parameter("name", "");
    
    int status_code = 500;
    std::string result = "";
    
    try {
        status_code =
            handler_DELETE(name);
    }
    catch(const MetalRefineryApiException& e) {
        std::tie(status_code, result) = handleMetalRefineryApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json"
    };
    static const std::string acceptTypes{
    };
    
    if (status_code == 400) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Invalid MetalRefinery variable supplied";
    
        returnResponse(session, 400, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 404) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "MetalRefinery not found";
    
        returnResponse(session, 404, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
}

// x-extension
void MetalRefineryNameResource::handler_GET_internal(const std::shared_ptr<restbed::Session> session) {
    const auto request = session->get_request();
    // Getting the path params
    std::string name = request->get_path_parameter("name", "");
    
    int status_code = 500;
    MetalRefinery resultObject = MetalRefinery{};
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_GET(name);
    }
    catch(const MetalRefineryApiException& e) {
        std::tie(status_code, result) = handleMetalRefineryApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json","application/xml",
    };
    static const std::string acceptTypes{
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        result = resultObject.toJsonString();
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 400) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Invalid MetalRefinery variable supplied";
    
        returnResponse(session, 400, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 404) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "MetalRefinery not found";
    
        returnResponse(session, 404, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
}
// x-extension
void MetalRefineryNameResource::handler_PUT_internal(const std::shared_ptr<restbed::Session> session) {
    const auto request = session->get_request();
    // body params or form params here from the body content string
    std::string bodyContent = extractBodyContent(session);
    auto metalRefinery = extractJsonModelBodyParam<MetalRefinery>(bodyContent);
    // Getting the path params
    std::string name = request->get_path_parameter("name", "");
    
    int status_code = 500;
    std::string result = "";
    
    try {
        status_code =
            handler_PUT(name, metalRefinery);
    }
    catch(const MetalRefineryApiException& e) {
        std::tie(status_code, result) = handleMetalRefineryApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json"
    };
    static const std::string acceptTypes{
        "application/json, application/xml, application/x-www-form-urlencoded, "
    };
    
    if (status_code == 0) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "successful operation";
    
        returnResponse(session, 0, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
}

int MetalRefineryNameResource::handler_DELETE(
        std::string & name)
{
    return handler_DELETE_func(name);
}

std::pair<int, MetalRefinery> MetalRefineryNameResource::handler_GET(
    std::string & name)
{
    return handler_GET_func(name);
}
int MetalRefineryNameResource::handler_PUT(
    std::string & name, MetalRefinery & metalRefinery)
{
    return handler_PUT_func(name, metalRefinery);
}

std::string MetalRefineryNameResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string MetalRefineryNameResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}

} /* namespace MetalRefineryApiResources */

MetalRefineryApi::MetalRefineryApi(std::shared_ptr<restbed::Service> const& restbedService)
: m_service(restbedService)
{
}

MetalRefineryApi::~MetalRefineryApi() {}

std::shared_ptr<MetalRefineryApiResources::MetalRefineryResource> MetalRefineryApi::getMetalRefineryResource() {
    if (!m_spMetalRefineryResource) {
        setResource(std::make_shared<MetalRefineryApiResources::MetalRefineryResource>());
    }
    return m_spMetalRefineryResource;
}
std::shared_ptr<MetalRefineryApiResources::MetalRefineryCreateWithListResource> MetalRefineryApi::getMetalRefineryCreateWithListResource() {
    if (!m_spMetalRefineryCreateWithListResource) {
        setResource(std::make_shared<MetalRefineryApiResources::MetalRefineryCreateWithListResource>());
    }
    return m_spMetalRefineryCreateWithListResource;
}
std::shared_ptr<MetalRefineryApiResources::MetalRefineryNameResource> MetalRefineryApi::getMetalRefineryNameResource() {
    if (!m_spMetalRefineryNameResource) {
        setResource(std::make_shared<MetalRefineryApiResources::MetalRefineryNameResource>());
    }
    return m_spMetalRefineryNameResource;
}
void MetalRefineryApi::setResource(std::shared_ptr<MetalRefineryApiResources::MetalRefineryResource> resource) {
    m_spMetalRefineryResource = resource;
    m_service->publish(m_spMetalRefineryResource);
}
void MetalRefineryApi::setResource(std::shared_ptr<MetalRefineryApiResources::MetalRefineryCreateWithListResource> resource) {
    m_spMetalRefineryCreateWithListResource = resource;
    m_service->publish(m_spMetalRefineryCreateWithListResource);
}
void MetalRefineryApi::setResource(std::shared_ptr<MetalRefineryApiResources::MetalRefineryNameResource> resource) {
    m_spMetalRefineryNameResource = resource;
    m_service->publish(m_spMetalRefineryNameResource);
}
void MetalRefineryApi::setMetalRefineryApiMetalRefineryResource(std::shared_ptr<MetalRefineryApiResources::MetalRefineryResource> spMetalRefineryResource) {
    m_spMetalRefineryResource = spMetalRefineryResource;
    m_service->publish(m_spMetalRefineryResource);
}
void MetalRefineryApi::setMetalRefineryApiMetalRefineryCreateWithListResource(std::shared_ptr<MetalRefineryApiResources::MetalRefineryCreateWithListResource> spMetalRefineryCreateWithListResource) {
    m_spMetalRefineryCreateWithListResource = spMetalRefineryCreateWithListResource;
    m_service->publish(m_spMetalRefineryCreateWithListResource);
}
void MetalRefineryApi::setMetalRefineryApiMetalRefineryNameResource(std::shared_ptr<MetalRefineryApiResources::MetalRefineryNameResource> spMetalRefineryNameResource) {
    m_spMetalRefineryNameResource = spMetalRefineryNameResource;
    m_service->publish(m_spMetalRefineryNameResource);
}


void MetalRefineryApi::publishDefaultResources() {
    if (!m_spMetalRefineryResource) {
        setResource(std::make_shared<MetalRefineryApiResources::MetalRefineryResource>());
    }
    if (!m_spMetalRefineryCreateWithListResource) {
        setResource(std::make_shared<MetalRefineryApiResources::MetalRefineryCreateWithListResource>());
    }
    if (!m_spMetalRefineryNameResource) {
        setResource(std::make_shared<MetalRefineryApiResources::MetalRefineryNameResource>());
    }
}

std::shared_ptr<restbed::Service> MetalRefineryApi::service() {
    return m_service;
}


}
}
}
}

