/**
 * API Inspector
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include <corvusoft/restbed/byte.hpp>
#include <corvusoft/restbed/string.hpp>
#include <corvusoft/restbed/settings.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/uri.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/algorithm/string.hpp>

#include "ReinforcementLearningAgentApi.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

namespace {
[[maybe_unused]]
std::string selectPreferredContentType(const std::vector<std::string>& contentTypes) {
    if (contentTypes.size() == 0) {
        return "application/json";
    }

    if (contentTypes.size() == 1) {
        return contentTypes.at(0);
    }

    static const std::array<std::string, 2> preferredTypes = {"json", "xml"};
    for (const auto& preferredType: preferredTypes) {
        const auto ret = std::find_if(contentTypes.cbegin(),
        contentTypes.cend(),
        [preferredType](const std::string& str) {
            return str.find(preferredType) != std::string::npos;});
        if (ret != contentTypes.cend()) {
            return *ret;
        }
    }

    return contentTypes.at(0);
}
}

ReinforcementLearningAgentApiException::ReinforcementLearningAgentApiException(int status_code, std::string what)
  : m_status(status_code),
    m_what(what)
{

}
int ReinforcementLearningAgentApiException::getStatus() const
{
    return m_status;
}
const char* ReinforcementLearningAgentApiException::what() const noexcept
{
    return m_what.c_str();
}


template<class MODEL_T>
MODEL_T extractJsonModelBodyParam(const std::string& bodyContent)
{
    std::stringstream sstream(bodyContent);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream, pt);

    auto model = MODEL_T(pt);
    return model;
}

template<class MODEL_T>
std::vector<MODEL_T> extractJsonArrayBodyParam(const std::string& bodyContent)
{
    std::stringstream sstream(bodyContent);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream, pt);

    auto arrayRet = std::vector<MODEL_T>();
    for (const auto& child: pt) {
        arrayRet.emplace_back(MODEL_T(child.second));
    }
    return arrayRet;
}

template <class KEY_T, class VAL_T>
std::string convertMapResponse(const std::map<KEY_T, VAL_T>& map)
{
    boost::property_tree::ptree pt;
    for(const auto &kv: map) {
    pt.push_back(boost::property_tree::ptree::value_type(
        boost::lexical_cast<std::string>(kv.first),
        boost::property_tree::ptree(
        boost::lexical_cast<std::string>(kv.second))));
    }
    std::stringstream sstream;
    write_json(sstream, pt);
    std::string result = sstream.str();
    return result;
}

namespace ReinforcementLearningAgentApiResources {
ReinforcementLearningAgentResource::ReinforcementLearningAgentResource(const std::string& context /* = "/openapi-jaxrs-server-1.0.0/api/v3" */)
{
	this->set_path(context + "/reinforcementLearningAgent");
	this->set_method_handler("POST",
		std::bind(&ReinforcementLearningAgentResource::handler_POST_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> ReinforcementLearningAgentResource::handleReinforcementLearningAgentApiException(const ReinforcementLearningAgentApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> ReinforcementLearningAgentResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> ReinforcementLearningAgentResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void ReinforcementLearningAgentResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void ReinforcementLearningAgentResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void ReinforcementLearningAgentResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void ReinforcementLearningAgentResource::handler_POST_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // body params or form params here from the body content string
    std::string bodyContent = extractBodyContent(session);
    auto reinforcementLearningAgent = extractJsonModelBodyParam<ReinforcementLearningAgent>(bodyContent);
    
    int status_code = 500;
    ReinforcementLearningAgent resultObject = ReinforcementLearningAgent{};
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_POST(reinforcementLearningAgent);
    }
    catch(const ReinforcementLearningAgentApiException& e) {
        std::tie(status_code, result) = handleReinforcementLearningAgentApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json","application/xml",
    };
    static const std::string acceptTypes{
        "application/json, application/xml, application/x-www-form-urlencoded, "
    };
    
    if (status_code == 0) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "successful operation";
    
        result = resultObject.toJsonString();
        returnResponse(session, 0, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
}


std::pair<int, ReinforcementLearningAgent> ReinforcementLearningAgentResource::handler_POST(
        ReinforcementLearningAgent & reinforcementLearningAgent)
{
    return handler_POST_func(reinforcementLearningAgent);
}


std::string ReinforcementLearningAgentResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string ReinforcementLearningAgentResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
ReinforcementLearningAgentCreateWithListResource::ReinforcementLearningAgentCreateWithListResource(const std::string& context /* = "/openapi-jaxrs-server-1.0.0/api/v3" */)
{
	this->set_path(context + "/reinforcementLearningAgent/createWithList");
	this->set_method_handler("POST",
		std::bind(&ReinforcementLearningAgentCreateWithListResource::handler_POST_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> ReinforcementLearningAgentCreateWithListResource::handleReinforcementLearningAgentApiException(const ReinforcementLearningAgentApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> ReinforcementLearningAgentCreateWithListResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> ReinforcementLearningAgentCreateWithListResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void ReinforcementLearningAgentCreateWithListResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void ReinforcementLearningAgentCreateWithListResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void ReinforcementLearningAgentCreateWithListResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void ReinforcementLearningAgentCreateWithListResource::handler_POST_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // body params or form params here from the body content string
    std::string bodyContent = extractBodyContent(session);
    auto reinforcementLearningAgent = extractJsonArrayBodyParam<ReinforcementLearningAgent>(bodyContent);
    
    int status_code = 500;
    ReinforcementLearningAgent resultObject = ReinforcementLearningAgent{};
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_POST(reinforcementLearningAgent);
    }
    catch(const ReinforcementLearningAgentApiException& e) {
        std::tie(status_code, result) = handleReinforcementLearningAgentApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json","application/xml",
    };
    static const std::string acceptTypes{
        "application/json, "
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        result = resultObject.toJsonString();
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 0) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "successful operation";
    
        returnResponse(session, 0, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
}


std::pair<int, ReinforcementLearningAgent> ReinforcementLearningAgentCreateWithListResource::handler_POST(
        std::vector<ReinforcementLearningAgent> & reinforcementLearningAgent)
{
    return handler_POST_func(reinforcementLearningAgent);
}


std::string ReinforcementLearningAgentCreateWithListResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string ReinforcementLearningAgentCreateWithListResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
ReinforcementLearningAgentNameResource::ReinforcementLearningAgentNameResource(const std::string& context /* = "/openapi-jaxrs-server-1.0.0/api/v3" */)
{
	this->set_path(context + "/reinforcementLearningAgent/{name: .*}");
	this->set_method_handler("DELETE",
		std::bind(&ReinforcementLearningAgentNameResource::handler_DELETE_internal, this,
			std::placeholders::_1));
	this->set_method_handler("GET",
		std::bind(&ReinforcementLearningAgentNameResource::handler_GET_internal, this,
			std::placeholders::_1));
	this->set_method_handler("PUT",
		std::bind(&ReinforcementLearningAgentNameResource::handler_PUT_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> ReinforcementLearningAgentNameResource::handleReinforcementLearningAgentApiException(const ReinforcementLearningAgentApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> ReinforcementLearningAgentNameResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> ReinforcementLearningAgentNameResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void ReinforcementLearningAgentNameResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void ReinforcementLearningAgentNameResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void ReinforcementLearningAgentNameResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void ReinforcementLearningAgentNameResource::handler_DELETE_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // Getting the path params
    std::string name = request->get_path_parameter("name", "");
    
    int status_code = 500;
    std::string result = "";
    
    try {
        status_code =
            handler_DELETE(name);
    }
    catch(const ReinforcementLearningAgentApiException& e) {
        std::tie(status_code, result) = handleReinforcementLearningAgentApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json"
    };
    static const std::string acceptTypes{
    };
    
    if (status_code == 400) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Invalid ReinforcementLearningAgent variable supplied";
    
        returnResponse(session, 400, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 404) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "ReinforcementLearningAgent not found";
    
        returnResponse(session, 404, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
}

// x-extension
void ReinforcementLearningAgentNameResource::handler_GET_internal(const std::shared_ptr<restbed::Session> session) {
    const auto request = session->get_request();
    // Getting the path params
    std::string name = request->get_path_parameter("name", "");
    
    int status_code = 500;
    ReinforcementLearningAgent resultObject = ReinforcementLearningAgent{};
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_GET(name);
    }
    catch(const ReinforcementLearningAgentApiException& e) {
        std::tie(status_code, result) = handleReinforcementLearningAgentApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json","application/xml",
    };
    static const std::string acceptTypes{
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        result = resultObject.toJsonString();
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 400) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Invalid ReinforcementLearningAgent variable supplied";
    
        returnResponse(session, 400, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 404) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "ReinforcementLearningAgent not found";
    
        returnResponse(session, 404, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
}
// x-extension
void ReinforcementLearningAgentNameResource::handler_PUT_internal(const std::shared_ptr<restbed::Session> session) {
    const auto request = session->get_request();
    // body params or form params here from the body content string
    std::string bodyContent = extractBodyContent(session);
    auto reinforcementLearningAgent = extractJsonModelBodyParam<ReinforcementLearningAgent>(bodyContent);
    // Getting the path params
    std::string name = request->get_path_parameter("name", "");
    
    int status_code = 500;
    std::string result = "";
    
    try {
        status_code =
            handler_PUT(name, reinforcementLearningAgent);
    }
    catch(const ReinforcementLearningAgentApiException& e) {
        std::tie(status_code, result) = handleReinforcementLearningAgentApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json"
    };
    static const std::string acceptTypes{
        "application/json, application/xml, application/x-www-form-urlencoded, "
    };
    
    if (status_code == 0) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "successful operation";
    
        returnResponse(session, 0, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
}

int ReinforcementLearningAgentNameResource::handler_DELETE(
        std::string & name)
{
    return handler_DELETE_func(name);
}

std::pair<int, ReinforcementLearningAgent> ReinforcementLearningAgentNameResource::handler_GET(
    std::string & name)
{
    return handler_GET_func(name);
}
int ReinforcementLearningAgentNameResource::handler_PUT(
    std::string & name, ReinforcementLearningAgent & reinforcementLearningAgent)
{
    return handler_PUT_func(name, reinforcementLearningAgent);
}

std::string ReinforcementLearningAgentNameResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string ReinforcementLearningAgentNameResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}

} /* namespace ReinforcementLearningAgentApiResources */

ReinforcementLearningAgentApi::ReinforcementLearningAgentApi(std::shared_ptr<restbed::Service> const& restbedService)
: m_service(restbedService)
{
}

ReinforcementLearningAgentApi::~ReinforcementLearningAgentApi() {}

std::shared_ptr<ReinforcementLearningAgentApiResources::ReinforcementLearningAgentResource> ReinforcementLearningAgentApi::getReinforcementLearningAgentResource() {
    if (!m_spReinforcementLearningAgentResource) {
        setResource(std::make_shared<ReinforcementLearningAgentApiResources::ReinforcementLearningAgentResource>());
    }
    return m_spReinforcementLearningAgentResource;
}
std::shared_ptr<ReinforcementLearningAgentApiResources::ReinforcementLearningAgentCreateWithListResource> ReinforcementLearningAgentApi::getReinforcementLearningAgentCreateWithListResource() {
    if (!m_spReinforcementLearningAgentCreateWithListResource) {
        setResource(std::make_shared<ReinforcementLearningAgentApiResources::ReinforcementLearningAgentCreateWithListResource>());
    }
    return m_spReinforcementLearningAgentCreateWithListResource;
}
std::shared_ptr<ReinforcementLearningAgentApiResources::ReinforcementLearningAgentNameResource> ReinforcementLearningAgentApi::getReinforcementLearningAgentNameResource() {
    if (!m_spReinforcementLearningAgentNameResource) {
        setResource(std::make_shared<ReinforcementLearningAgentApiResources::ReinforcementLearningAgentNameResource>());
    }
    return m_spReinforcementLearningAgentNameResource;
}
void ReinforcementLearningAgentApi::setResource(std::shared_ptr<ReinforcementLearningAgentApiResources::ReinforcementLearningAgentResource> resource) {
    m_spReinforcementLearningAgentResource = resource;
    m_service->publish(m_spReinforcementLearningAgentResource);
}
void ReinforcementLearningAgentApi::setResource(std::shared_ptr<ReinforcementLearningAgentApiResources::ReinforcementLearningAgentCreateWithListResource> resource) {
    m_spReinforcementLearningAgentCreateWithListResource = resource;
    m_service->publish(m_spReinforcementLearningAgentCreateWithListResource);
}
void ReinforcementLearningAgentApi::setResource(std::shared_ptr<ReinforcementLearningAgentApiResources::ReinforcementLearningAgentNameResource> resource) {
    m_spReinforcementLearningAgentNameResource = resource;
    m_service->publish(m_spReinforcementLearningAgentNameResource);
}
void ReinforcementLearningAgentApi::setReinforcementLearningAgentApiReinforcementLearningAgentResource(std::shared_ptr<ReinforcementLearningAgentApiResources::ReinforcementLearningAgentResource> spReinforcementLearningAgentResource) {
    m_spReinforcementLearningAgentResource = spReinforcementLearningAgentResource;
    m_service->publish(m_spReinforcementLearningAgentResource);
}
void ReinforcementLearningAgentApi::setReinforcementLearningAgentApiReinforcementLearningAgentCreateWithListResource(std::shared_ptr<ReinforcementLearningAgentApiResources::ReinforcementLearningAgentCreateWithListResource> spReinforcementLearningAgentCreateWithListResource) {
    m_spReinforcementLearningAgentCreateWithListResource = spReinforcementLearningAgentCreateWithListResource;
    m_service->publish(m_spReinforcementLearningAgentCreateWithListResource);
}
void ReinforcementLearningAgentApi::setReinforcementLearningAgentApiReinforcementLearningAgentNameResource(std::shared_ptr<ReinforcementLearningAgentApiResources::ReinforcementLearningAgentNameResource> spReinforcementLearningAgentNameResource) {
    m_spReinforcementLearningAgentNameResource = spReinforcementLearningAgentNameResource;
    m_service->publish(m_spReinforcementLearningAgentNameResource);
}


void ReinforcementLearningAgentApi::publishDefaultResources() {
    if (!m_spReinforcementLearningAgentResource) {
        setResource(std::make_shared<ReinforcementLearningAgentApiResources::ReinforcementLearningAgentResource>());
    }
    if (!m_spReinforcementLearningAgentCreateWithListResource) {
        setResource(std::make_shared<ReinforcementLearningAgentApiResources::ReinforcementLearningAgentCreateWithListResource>());
    }
    if (!m_spReinforcementLearningAgentNameResource) {
        setResource(std::make_shared<ReinforcementLearningAgentApiResources::ReinforcementLearningAgentNameResource>());
    }
}

std::shared_ptr<restbed::Service> ReinforcementLearningAgentApi::service() {
    return m_service;
}


}
}
}
}

