=begin
API Inspector

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class Dell274kUhDMonitorS2721QSController < ApplicationController

  def create_dell274k_uhd_monitor_s2721qs
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def create_dell274k_uhd_monitor_s2721qss_with_list_input
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def delete_dell274k_uhd_monitor_s2721qs
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_dell274k_uhd_monitor_s2721qs_by_name
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def update_dell274k_uhd_monitor_s2721qs
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
