=begin
API Inspector

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class LenovoLegionTower7iGen8DesktopIntelCoreI9ProcessorController < ApplicationController

  def create_lenovo_legion_tower7i_gen8_desktop_intel_core_i9_processor
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def create_lenovo_legion_tower7i_gen8_desktop_intel_core_i9_processors_with_list_input
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def delete_lenovo_legion_tower7i_gen8_desktop_intel_core_i9_processor
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_lenovo_legion_tower7i_gen8_desktop_intel_core_i9_processor_by_name
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def update_lenovo_legion_tower7i_gen8_desktop_intel_core_i9_processor
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
