=begin
API Inspector

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "alienware_aurora_r15_gaming_desktop".pluralize.to_sym, id: false do |t|
      t.string :n_vidia_graphics
      t.integer :h_dmi_outputs
      t.boolean :windows10_compatible
      t.string :a_wcc_interface
      t.boolean :multi_monitor_support
      t.boolean :heat_management_system
      t.Float :_1_tbss_d_storage
      t.string :_8th_gen_processor
      t.boolean :high_definition_audio_out
      t.integer :g_po_fb8
      t.string :g_po_e23
      t.boolean :liquid_cooling_option
      t.boolean :built_in_wi_fi
      t.boolean :customizable_lighting
      t.integer :max_ra_m_capacity
      t.integer :_7_us_b_ports
      t.boolean :smart_airflow_technology

      t.timestamps
    end

    create_table "cat".pluralize.to_sym, id: false do |t|
      t.integer :sleeps_hours
      t.string :eye_color
      t.boolean :furry_tail
      t.integer :age
      t.Float :jump_height
      t.boolean :perches_places
      t.boolean :moody_temperament
      t.integer :tail_length
      t.string :coat_pattern
      t.boolean :likes_people
      t.integer :meow_frequency
      t.string :fur_color
      t.integer :g_po_449
      t.Float :weight
      t.string :g_po_256
      t.boolean :has_claws
      t.string :breed

      t.timestamps
    end

    create_table "dell274k_uhd_monitor_s2721qs".pluralize.to_sym, id: false do |t|
      t.boolean :integrated_speakers
      t.integer :color_depth
      t.integer :response_time
      t.integer :resolution
      t.integer :viewing_angle
      t.boolean :tiltable_stand
      t.Float :price_range
      t.integer :screen_size
      t.integer :brightness
      t.string :color_gamut
      t.integer :g_po_428
      t.string :panel_type
      t.boolean :v_esa_mountable
      t.string :g_po_cf2
      t.string :connectivity_ports
      t.Float :contrast_ratio
      t.Float :aspect_ratio

      t.timestamps
    end

    create_table "dog".pluralize.to_sym, id: false do |t|
      t.boolean :affectionate
      t.boolean :loyal
      t.string :breed
      t.Float :weight
      t.Float :height
      t.boolean :noisy
      t.boolean :energetic
      t.boolean :friendly
      t.boolean :healthy
      t.boolean :vaccinated
      t.integer :g_po_df0
      t.integer :age
      t.boolean :intelligent
      t.string :g_po_e4a
      t.string :gender
      t.string :colour

      t.timestamps
    end

    create_table "error".pluralize.to_sym, id: false do |t|
      t.integer :code
      t.string :message

      t.timestamps
    end

    create_table "lenovo_legion_tower7i_gen8_desktop_intel_core_i9_processor".pluralize.to_sym, id: false do |t|
      t.integer :ports_number
      t.string :card_reader_type
      t.integer :generation
      t.string :processor
      t.integer :storage
      t.integer :memory
      t.Float :speed
      t.integer :power_supply_unit_size_watts
      t.integer :g_po_a87
      t.string :color_scheme_option1and2
      t.integer :cores
      t.string :graphics
      t.string :g_po_181
      t.string :operating_system
      t.string :model
      t.string :brand
      t.string :optical_drive_type

      t.timestamps
    end

    create_table "user".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :username
      t.string :first_name
      t.string :last_name
      t.string :email
      t.string :password
      t.string :phone
      t.integer :user_status

      t.timestamps
    end

  end
end
