/**
 * API Inspector
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Credit model module.
 * @module model/Credit
 * @version 1.0.0
 */
class Credit {
    /**
     * Constructs a new <code>Credit</code>.
     * @alias module:model/Credit
     * @param name {String} name attribute of this model
     * @param id {Number} id attribute of this model
     */
    constructor(name, id) { 
        
        Credit.initialize(this, name, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, id) { 
        obj['name'] = name || '03fd59d1-66d2-4cf6-b1bb-b700633e97ba';
        obj['id'] = id || 1701;
    }

    /**
     * Constructs a <code>Credit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Credit} obj Optional instance to populate.
     * @return {module:model/Credit} The populated <code>Credit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Credit();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Credit</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Credit</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Credit.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

Credit.RequiredProperties = ["name", "id"];

/**
 * name attribute of this model
 * @member {String} name
 * @default '03fd59d1-66d2-4cf6-b1bb-b700633e97ba'
 */
Credit.prototype['name'] = '03fd59d1-66d2-4cf6-b1bb-b700633e97ba';

/**
 * id attribute of this model
 * @member {Number} id
 * @default 1701
 */
Credit.prototype['id'] = 1701;






export default Credit;

